server:
  port: 8999

logging:
  path: logs
  file: logger.log

spring:
  application:
    name: Chapter13Application
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://120.77.150.79:3306/ssh?useSSL=true
    username: root
    password: Mysqlroot,1

mybatis:
  type-aliases-package: top.rex.code.model
  mapper-locations:
    - mapper/*